name: local_mock_apirest
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  json_schema: ^5.1.7
  shelf: ^1.4.2
  yaml: ^3.1.2
# path: ^1.8.0
dev_dependencies:
  http: ^1.2.1
  lints: ^3.0.0
  test: ^1.24.0
