name: local_mock_apirest
description: A local mock server that uses YAML files to define routes, methods, and responses with automatic restart on file changes.
version: 1.0.0
repository: https://github.com/carmonac/local_mock_apirest
homepage: https://github.com/carmonac/local_mock_apirest
environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  json_schema: ^5.1.7
  shelf: ^1.4.2
  yaml: ^3.1.2
# path: ^1.8.0
dev_dependencies:
  http: ^1.2.1
  lints: ^5.1.1
  test: ^1.24.0

executables:
  local_mock_apirest: local_mock_apirest
